### ISSUE TITLE
Update main branch from stage.

### ISSUE THREAD

**Issue by sandeep-ps** [htrc/torchlite-frontend#147]

**Comment by jswatsch** [comment]
From slack: After today morning's meeting, I updated the Torchlite fronted and EF-API to point to the latest main branch, and also brought all changes from stage to the main branch in those repositories (EF-API was already in sync). The production instance (https://torchlite.htrc.illinois.edu/) is almost running fine, barring the MongoDB restart issue which is causing some performance degradation and is still being investigated. (edited)
