### ISSUE TITLE
Extracted features for the map widget

### ISSUE THREAD

**Issue by jswatsch** [htrc/torchlite-frontend#20]
What extracted features does Cliff need to provide David for the map widget. 

From our meeting on Wednesday, the current data needed is:

- author name
- birthplace
- gps coordinates

**Comment by jswatsch** [comment]
Specified in issue 49: https://github.com/htrc/torchlite-app/issues/49

**Comment by jchristie01** [comment]
Timeline widget has been implemented on the frontend
